name: Build
on: push

env:
  tag: patch-5.15
  library_repo: thewakingsands/ffxiv-datamining-cn
  teamcraft_repo: ffxiv-teamcraft/ffxiv-teamcraft
  teamcraft_fork: zhyupe/ffxiv-teamcraft

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch library
      run: git clone --branch $tag --depth 1 https://github.com/${library_repo}.git library
      
    - name: Clone teamcraft
      run: git clone --branch staging https://github.com/${teamcraft_repo}.git teamcraft
      
    - name: Check node version
      run: node -v

    - name: Replace source directory
      run: |
        sed -i "s/\/library\/[0-9.]\+\//\/library\//" teamcraft/data-extraction/data-exporter/config/zh.js
        sed -i "s/file: 'chs'/file: ''/" teamcraft/data-extraction/data-exporter/config/zh.js
        
      
    - name: Run data generator
      run: node teamcraft/data-extraction/data-exporter/index-zh.js
      
    - name: Setting fork as origin
      run: |
        cd teamcraft
        git remote set-url origin https://github.com/${teamcraft_fork}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.WORKER_ACCESS_KEY }}
        path: teamcraft
        commit-message: "feat(data): update for cn $tag"
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        # request-to-parent: true
        branch: ci/zh/datamining-${{ github.run_id }}-${{ github.run_number }}
        base: staging
        title: "feat(data): update for cn $tag"
        body: |
          This PR is automatically generated by [ffxiv-datamining-worker](https://github.com/zhyupe/ffxiv-datamining-worker)
